environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn run build

test_script:
  - node --version
  - yarn --version
  - yarn test

cache:
  - node_modules
  - '%LOCALAPPDATA%/Yarn'
