#!/bin/sh
set -eu

# Ensure the downloaded Ruby version is used
export PATH="$LAMBDA_RUNTIME_DIR/bin:$PATH"

# Execute the "ruby" runtime bootstrap
export LAMBDA_RUNTIME_DIR="$(dirname "$0")/../ruby"

exec "$LAMBDA_RUNTIME_DIR/bootstrap" "$@"
