name: CI

on:
  push:
    branches:
      - main
    tags:
      - "!*"
  pull_request:

jobs:
  build:
    name: Test Node.js ${{ matrix.node }} on ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [20, 22, 24]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ matrix.node }}

      - name: Print Node.js Version
        run: node --version

      - name: Use pnpm
        run: npm install -g pnpm@10.1.0 && pnpm --version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run "build" step
        run: pnpm build

      - name: Run tests
        run: pnpm test

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 22.14.0

      - name: Use pnpm
        run: npm install -g pnpm@10.1.0 && pnpm --version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release@25.0.9
